baseURL = "http://example.org/"
languageCode = "en-us"
title = 'Club Gamma Open Source'
theme = "pulp"

[taxonomies]
  series = "series"

[params]
    author = "Club Gamma"
    avatar = "logo.jpeg"
    favicon = "favicon.ico"
    description = """
        Welcome to the Club Gamma.
        Click on the "edit" icon below to see contributors list. Fork the repo and check the README.md
    """
    publicationYear = "2021"

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "contributors"
    pre = "<i class='fa fa-edit fa-lg'></i>"
    url = "./contributors"
    weight = 1


[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/club_gamma"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/clubgamma/"
    weight = 30


[[menu.main]]
    identifier = "youtube"
    # name = "Youtube"
    pre = "<i class='fab fa-youtube fa-lg'></i>"
    url = "https://www.youtube.com/channel/UCFO_j0Kml2tT3aFgVUSYGxQ"
    weight = 32
[[menu.main]]
    identifier = "instagram"
    # name = "Instagram"
    pre = "<i class='fab fa-instagram fa-lg'></i>"
    url = "https://www.instagram.com/club_gamma/"
    weight = 33


